/* tslint:disable */
/* eslint-disable */
/**
 * MusicNewsWatcher.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlbumDto
 */
export interface AlbumDto {
    /**
     * 
     * @type {number}
     * @memberof AlbumDto
     */
    albumId?: number;
    /**
     * 
     * @type {number}
     * @memberof AlbumDto
     */
    artistId?: number;
    /**
     * 
     * @type {string}
     * @memberof AlbumDto
     */
    title?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AlbumDto
     */
    created?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AlbumDto
     */
    isViewed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AlbumDto
     */
    image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlbumDto
     */
    uri?: string | null;
}

/**
 * Check if a given object implements the AlbumDto interface.
 */
export function instanceOfAlbumDto(value: object): value is AlbumDto {
    return true;
}

export function AlbumDtoFromJSON(json: any): AlbumDto {
    return AlbumDtoFromJSONTyped(json, false);
}

export function AlbumDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumDto {
    if (json == null) {
        return json;
    }
    return {
        
        'albumId': json['albumId'] == null ? undefined : json['albumId'],
        'artistId': json['artistId'] == null ? undefined : json['artistId'],
        'title': json['title'] == null ? undefined : json['title'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'isViewed': json['isViewed'] == null ? undefined : json['isViewed'],
        'image': json['image'] == null ? undefined : json['image'],
        'uri': json['uri'] == null ? undefined : json['uri'],
    };
}

export function AlbumDtoToJSON(json: any): AlbumDto {
    return AlbumDtoToJSONTyped(json, false);
}

export function AlbumDtoToJSONTyped(value?: AlbumDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'albumId': value['albumId'],
        'artistId': value['artistId'],
        'title': value['title'],
        'created': value['created'] == null ? value['created'] : value['created'].toISOString(),
        'isViewed': value['isViewed'],
        'image': value['image'],
        'uri': value['uri'],
    };
}

