/* tslint:disable */
/* eslint-disable */
/**
 * MusicNewsWatcher.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtistDto
 */
export interface ArtistDto {
    /**
     * 
     * @type {number}
     * @memberof ArtistDto
     */
    musicProviderId?: number;
    /**
     * 
     * @type {number}
     * @memberof ArtistDto
     */
    artistId?: number;
    /**
     * 
     * @type {string}
     * @memberof ArtistDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArtistDto
     */
    uri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArtistDto
     */
    image?: string | null;
}

/**
 * Check if a given object implements the ArtistDto interface.
 */
export function instanceOfArtistDto(value: object): value is ArtistDto {
    return true;
}

export function ArtistDtoFromJSON(json: any): ArtistDto {
    return ArtistDtoFromJSONTyped(json, false);
}

export function ArtistDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistDto {
    if (json == null) {
        return json;
    }
    return {
        
        'musicProviderId': json['musicProviderId'] == null ? undefined : json['musicProviderId'],
        'artistId': json['artistId'] == null ? undefined : json['artistId'],
        'name': json['name'] == null ? undefined : json['name'],
        'uri': json['uri'] == null ? undefined : json['uri'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function ArtistDtoToJSON(json: any): ArtistDto {
    return ArtistDtoToJSONTyped(json, false);
}

export function ArtistDtoToJSONTyped(value?: ArtistDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'musicProviderId': value['musicProviderId'],
        'artistId': value['artistId'],
        'name': value['name'],
        'uri': value['uri'],
        'image': value['image'],
    };
}

