/* tslint:disable */
/* eslint-disable */
/**
 * MusicNewsWatcher.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateArtistDto
 */
export interface CreateArtistDto {
    /**
     * 
     * @type {number}
     * @memberof CreateArtistDto
     */
    musicProviderId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateArtistDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateArtistDto
     */
    uri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateArtistDto
     */
    image?: string | null;
}

/**
 * Check if a given object implements the CreateArtistDto interface.
 */
export function instanceOfCreateArtistDto(value: object): value is CreateArtistDto {
    return true;
}

export function CreateArtistDtoFromJSON(json: any): CreateArtistDto {
    return CreateArtistDtoFromJSONTyped(json, false);
}

export function CreateArtistDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateArtistDto {
    if (json == null) {
        return json;
    }
    return {
        
        'musicProviderId': json['musicProviderId'] == null ? undefined : json['musicProviderId'],
        'name': json['name'] == null ? undefined : json['name'],
        'uri': json['uri'] == null ? undefined : json['uri'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function CreateArtistDtoToJSON(json: any): CreateArtistDto {
    return CreateArtistDtoToJSONTyped(json, false);
}

export function CreateArtistDtoToJSONTyped(value?: CreateArtistDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'musicProviderId': value['musicProviderId'],
        'name': value['name'],
        'uri': value['uri'],
        'image': value['image'],
    };
}

