/* tslint:disable */
/* eslint-disable */
/**
 * MusicNewsWatcher.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MusicProviderDto
 */
export interface MusicProviderDto {
    /**
     * 
     * @type {number}
     * @memberof MusicProviderDto
     */
    musicProviderId?: number;
    /**
     * 
     * @type {string}
     * @memberof MusicProviderDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MusicProviderDto
     */
    image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MusicProviderDto
     */
    uri?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MusicProviderDto
     */
    totalArtists?: number;
}

/**
 * Check if a given object implements the MusicProviderDto interface.
 */
export function instanceOfMusicProviderDto(value: object): value is MusicProviderDto {
    return true;
}

export function MusicProviderDtoFromJSON(json: any): MusicProviderDto {
    return MusicProviderDtoFromJSONTyped(json, false);
}

export function MusicProviderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicProviderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'musicProviderId': json['musicProviderId'] == null ? undefined : json['musicProviderId'],
        'name': json['name'] == null ? undefined : json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'uri': json['uri'] == null ? undefined : json['uri'],
        'totalArtists': json['totalArtists'] == null ? undefined : json['totalArtists'],
    };
}

export function MusicProviderDtoToJSON(json: any): MusicProviderDto {
    return MusicProviderDtoToJSONTyped(json, false);
}

export function MusicProviderDtoToJSONTyped(value?: MusicProviderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'musicProviderId': value['musicProviderId'],
        'name': value['name'],
        'image': value['image'],
        'uri': value['uri'],
        'totalArtists': value['totalArtists'],
    };
}

