/* tslint:disable */
/* eslint-disable */
/**
 * MusicNewsWatcher.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackDownloadHistoryDto
 */
export interface TrackDownloadHistoryDto {
    /**
     * 
     * @type {string}
     * @memberof TrackDownloadHistoryDto
     */
    artistName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackDownloadHistoryDto
     */
    albumName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackDownloadHistoryDto
     */
    trackName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TrackDownloadHistoryDto
     */
    started?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrackDownloadHistoryDto
     */
    finished?: Date;
    /**
     * 
     * @type {number}
     * @memberof TrackDownloadHistoryDto
     */
    fileSizeInBytes?: number;
}

/**
 * Check if a given object implements the TrackDownloadHistoryDto interface.
 */
export function instanceOfTrackDownloadHistoryDto(value: object): value is TrackDownloadHistoryDto {
    return true;
}

export function TrackDownloadHistoryDtoFromJSON(json: any): TrackDownloadHistoryDto {
    return TrackDownloadHistoryDtoFromJSONTyped(json, false);
}

export function TrackDownloadHistoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackDownloadHistoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'artistName': json['artistName'] == null ? undefined : json['artistName'],
        'albumName': json['albumName'] == null ? undefined : json['albumName'],
        'trackName': json['trackName'] == null ? undefined : json['trackName'],
        'started': json['started'] == null ? undefined : (new Date(json['started'])),
        'finished': json['finished'] == null ? undefined : (new Date(json['finished'])),
        'fileSizeInBytes': json['fileSizeInBytes'] == null ? undefined : json['fileSizeInBytes'],
    };
}

export function TrackDownloadHistoryDtoToJSON(json: any): TrackDownloadHistoryDto {
    return TrackDownloadHistoryDtoToJSONTyped(json, false);
}

export function TrackDownloadHistoryDtoToJSONTyped(value?: TrackDownloadHistoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artistName': value['artistName'],
        'albumName': value['albumName'],
        'trackName': value['trackName'],
        'started': value['started'] == null ? value['started'] : value['started'].toISOString(),
        'finished': value['finished'] == null ? value['finished'] : value['finished'].toISOString(),
        'fileSizeInBytes': value['fileSizeInBytes'],
    };
}

