/* tslint:disable */
/* eslint-disable */
/**
 * MusicNewsWatcher.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackDownloadHistoryRequest
 */
export interface TrackDownloadHistoryRequest {
    /**
     * 
     * @type {number}
     * @memberof TrackDownloadHistoryRequest
     */
    trackId?: number;
    /**
     * 
     * @type {Date}
     * @memberof TrackDownloadHistoryRequest
     */
    started?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrackDownloadHistoryRequest
     */
    finished?: Date;
    /**
     * 
     * @type {number}
     * @memberof TrackDownloadHistoryRequest
     */
    fileSizeInBytes?: number;
}

/**
 * Check if a given object implements the TrackDownloadHistoryRequest interface.
 */
export function instanceOfTrackDownloadHistoryRequest(value: object): value is TrackDownloadHistoryRequest {
    return true;
}

export function TrackDownloadHistoryRequestFromJSON(json: any): TrackDownloadHistoryRequest {
    return TrackDownloadHistoryRequestFromJSONTyped(json, false);
}

export function TrackDownloadHistoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackDownloadHistoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'trackId': json['trackId'] == null ? undefined : json['trackId'],
        'started': json['started'] == null ? undefined : (new Date(json['started'])),
        'finished': json['finished'] == null ? undefined : (new Date(json['finished'])),
        'fileSizeInBytes': json['fileSizeInBytes'] == null ? undefined : json['fileSizeInBytes'],
    };
}

export function TrackDownloadHistoryRequestToJSON(json: any): TrackDownloadHistoryRequest {
    return TrackDownloadHistoryRequestToJSONTyped(json, false);
}

export function TrackDownloadHistoryRequestToJSONTyped(value?: TrackDownloadHistoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trackId': value['trackId'],
        'started': value['started'] == null ? value['started'] : value['started'].toISOString(),
        'finished': value['finished'] == null ? value['finished'] : value['finished'].toISOString(),
        'fileSizeInBytes': value['fileSizeInBytes'],
    };
}

