<Project Sdk="Microsoft.Build.NoTargets/3.7.0">
  <PropertyGroup>
    <ProjectName>MusicNewsWatcher.Web</ProjectName>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="src\conponents\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="src\api\client.ts\.openapi-generator\FILES" />
    <None Include="src\api\client.ts\.openapi-generator\VERSION" />
  </ItemGroup>
</Project>