<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Json"  />
		<PackageReference Include="Microsoft.Extensions.Hosting"  />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore"  />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets"  />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MusicNewsWatcher.Core\MusicNewsWatcher.Core.csproj" />
		<ProjectReference Include="..\MusicNewsWatcher.TelegramBot\MusicNewsWatcher.TelegramBot.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="appsettings.json" />
		<Resource Include="Program.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
