/* tslint:disable */
/* eslint-disable */
/**
 * MusicNewsWatcher.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TrackDownloadHistoryDto,
  TrackDownloadHistoryRequest,
} from '../models/index';
import {
    TrackDownloadHistoryDtoFromJSON,
    TrackDownloadHistoryDtoToJSON,
    TrackDownloadHistoryRequestFromJSON,
    TrackDownloadHistoryRequestToJSON,
} from '../models/index';

export interface ApiDownloadHistoryGetRequest {
    limit?: number;
}

export interface ApiDownloadHistoryPostRequest {
    trackDownloadHistoryRequest?: TrackDownloadHistoryRequest;
}

/**
 * 
 */
export class DownloadHistoryApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiDownloadHistoryGet without sending the request
     */
    async apiDownloadHistoryGetRequestOpts(requestParameters: ApiDownloadHistoryGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/download-history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiDownloadHistoryGetRaw(requestParameters: ApiDownloadHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TrackDownloadHistoryDto>>> {
        const requestOptions = await this.apiDownloadHistoryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrackDownloadHistoryDtoFromJSON));
    }

    /**
     */
    async apiDownloadHistoryGet(requestParameters: ApiDownloadHistoryGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TrackDownloadHistoryDto>> {
        const response = await this.apiDownloadHistoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDownloadHistoryPost without sending the request
     */
    async apiDownloadHistoryPostRequestOpts(requestParameters: ApiDownloadHistoryPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/download-history`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TrackDownloadHistoryRequestToJSON(requestParameters['trackDownloadHistoryRequest']),
        };
    }

    /**
     */
    async apiDownloadHistoryPostRaw(requestParameters: ApiDownloadHistoryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiDownloadHistoryPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiDownloadHistoryPost(requestParameters: ApiDownloadHistoryPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDownloadHistoryPostRaw(requestParameters, initOverrides);
    }

}
