/* tslint:disable */
/* eslint-disable */
/**
 * MusicNewsWatcher.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlbumDto,
  ArtistDto,
  CreateArtistDto,
  MusicProviderDto,
} from '../models/index';
import {
    AlbumDtoFromJSON,
    AlbumDtoToJSON,
    ArtistDtoFromJSON,
    ArtistDtoToJSON,
    CreateArtistDtoFromJSON,
    CreateArtistDtoToJSON,
    MusicProviderDtoFromJSON,
    MusicProviderDtoToJSON,
} from '../models/index';

export interface ApiAlbumsAlbumIdProviderProviderIdGetRequest {
    albumId: number;
    providerId: number;
}

export interface ApiArtistsArtistIdAlbumsGetRequest {
    artistId: number;
}

export interface ApiArtistsArtistIdDeleteRequest {
    artistId: number;
}

export interface ApiArtistsArtistIdPutRequest {
    artistId: number;
    artistDto?: ArtistDto;
}

export interface ApiArtistsArtistIdRefreshAlbumsPostRequest {
    artistId: number;
}

export interface ApiArtistsPostRequest {
    createArtistDto?: CreateArtistDto;
}

export interface ApiProvidersProviderIdArtistsGetRequest {
    providerId: number;
}

/**
 * 
 */
export class MusicNewsWatcherApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiAlbumsAlbumIdProviderProviderIdGet without sending the request
     */
    async apiAlbumsAlbumIdProviderProviderIdGetRequestOpts(requestParameters: ApiAlbumsAlbumIdProviderProviderIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['albumId'] == null) {
            throw new runtime.RequiredError(
                'albumId',
                'Required parameter "albumId" was null or undefined when calling apiAlbumsAlbumIdProviderProviderIdGet().'
            );
        }

        if (requestParameters['providerId'] == null) {
            throw new runtime.RequiredError(
                'providerId',
                'Required parameter "providerId" was null or undefined when calling apiAlbumsAlbumIdProviderProviderIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/albums/{album_id}/provider/{provider_id}`;
        urlPath = urlPath.replace(`{${"album_id"}}`, encodeURIComponent(String(requestParameters['albumId'])));
        urlPath = urlPath.replace(`{${"provider_id"}}`, encodeURIComponent(String(requestParameters['providerId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiAlbumsAlbumIdProviderProviderIdGetRaw(requestParameters: ApiAlbumsAlbumIdProviderProviderIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlbumDto>>> {
        const requestOptions = await this.apiAlbumsAlbumIdProviderProviderIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlbumDtoFromJSON));
    }

    /**
     */
    async apiAlbumsAlbumIdProviderProviderIdGet(requestParameters: ApiAlbumsAlbumIdProviderProviderIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlbumDto>> {
        const response = await this.apiAlbumsAlbumIdProviderProviderIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiArtistsArtistIdAlbumsGet without sending the request
     */
    async apiArtistsArtistIdAlbumsGetRequestOpts(requestParameters: ApiArtistsArtistIdAlbumsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['artistId'] == null) {
            throw new runtime.RequiredError(
                'artistId',
                'Required parameter "artistId" was null or undefined when calling apiArtistsArtistIdAlbumsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/artists/{artist_id}/albums`;
        urlPath = urlPath.replace(`{${"artist_id"}}`, encodeURIComponent(String(requestParameters['artistId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiArtistsArtistIdAlbumsGetRaw(requestParameters: ApiArtistsArtistIdAlbumsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlbumDto>>> {
        const requestOptions = await this.apiArtistsArtistIdAlbumsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlbumDtoFromJSON));
    }

    /**
     */
    async apiArtistsArtistIdAlbumsGet(requestParameters: ApiArtistsArtistIdAlbumsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlbumDto>> {
        const response = await this.apiArtistsArtistIdAlbumsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiArtistsArtistIdDelete without sending the request
     */
    async apiArtistsArtistIdDeleteRequestOpts(requestParameters: ApiArtistsArtistIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['artistId'] == null) {
            throw new runtime.RequiredError(
                'artistId',
                'Required parameter "artistId" was null or undefined when calling apiArtistsArtistIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/artists/{artist_id}`;
        urlPath = urlPath.replace(`{${"artist_id"}}`, encodeURIComponent(String(requestParameters['artistId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiArtistsArtistIdDeleteRaw(requestParameters: ApiArtistsArtistIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiArtistsArtistIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiArtistsArtistIdDelete(requestParameters: ApiArtistsArtistIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiArtistsArtistIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiArtistsArtistIdPut without sending the request
     */
    async apiArtistsArtistIdPutRequestOpts(requestParameters: ApiArtistsArtistIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['artistId'] == null) {
            throw new runtime.RequiredError(
                'artistId',
                'Required parameter "artistId" was null or undefined when calling apiArtistsArtistIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/artists/{artist_id}`;
        urlPath = urlPath.replace(`{${"artist_id"}}`, encodeURIComponent(String(requestParameters['artistId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ArtistDtoToJSON(requestParameters['artistDto']),
        };
    }

    /**
     */
    async apiArtistsArtistIdPutRaw(requestParameters: ApiArtistsArtistIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistDto>> {
        const requestOptions = await this.apiArtistsArtistIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiArtistsArtistIdPut(requestParameters: ApiArtistsArtistIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistDto> {
        const response = await this.apiArtistsArtistIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiArtistsArtistIdRefreshAlbumsPost without sending the request
     */
    async apiArtistsArtistIdRefreshAlbumsPostRequestOpts(requestParameters: ApiArtistsArtistIdRefreshAlbumsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['artistId'] == null) {
            throw new runtime.RequiredError(
                'artistId',
                'Required parameter "artistId" was null or undefined when calling apiArtistsArtistIdRefreshAlbumsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/artists/{artist_id}/refresh-albums`;
        urlPath = urlPath.replace(`{${"artist_id"}}`, encodeURIComponent(String(requestParameters['artistId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiArtistsArtistIdRefreshAlbumsPostRaw(requestParameters: ApiArtistsArtistIdRefreshAlbumsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiArtistsArtistIdRefreshAlbumsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiArtistsArtistIdRefreshAlbumsPost(requestParameters: ApiArtistsArtistIdRefreshAlbumsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiArtistsArtistIdRefreshAlbumsPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiArtistsPost without sending the request
     */
    async apiArtistsPostRequestOpts(requestParameters: ApiArtistsPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/artists`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateArtistDtoToJSON(requestParameters['createArtistDto']),
        };
    }

    /**
     */
    async apiArtistsPostRaw(requestParameters: ApiArtistsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistDto>> {
        const requestOptions = await this.apiArtistsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiArtistsPost(requestParameters: ApiArtistsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistDto> {
        const response = await this.apiArtistsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiProvidersGet without sending the request
     */
    async apiProvidersGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/providers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiProvidersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MusicProviderDto>>> {
        const requestOptions = await this.apiProvidersGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MusicProviderDtoFromJSON));
    }

    /**
     */
    async apiProvidersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MusicProviderDto>> {
        const response = await this.apiProvidersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiProvidersProviderIdArtistsGet without sending the request
     */
    async apiProvidersProviderIdArtistsGetRequestOpts(requestParameters: ApiProvidersProviderIdArtistsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['providerId'] == null) {
            throw new runtime.RequiredError(
                'providerId',
                'Required parameter "providerId" was null or undefined when calling apiProvidersProviderIdArtistsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/providers/{provider_id}/artists`;
        urlPath = urlPath.replace(`{${"provider_id"}}`, encodeURIComponent(String(requestParameters['providerId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiProvidersProviderIdArtistsGetRaw(requestParameters: ApiProvidersProviderIdArtistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ArtistDto>>> {
        const requestOptions = await this.apiProvidersProviderIdArtistsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ArtistDtoFromJSON));
    }

    /**
     */
    async apiProvidersProviderIdArtistsGet(requestParameters: ApiProvidersProviderIdArtistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ArtistDto>> {
        const response = await this.apiProvidersProviderIdArtistsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiStatusGet without sending the request
     */
    async apiStatusGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiStatusGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiStatusGetRaw(initOverrides);
    }

}
